language: php

php:
  - 7.0
  - 7.1

before_install:
  - composer selfupdate

before_script:
  - composer install
  - vendor/bin/doctrine orm:schema-tool:update --force

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls

script: phpunit --configuration phpunit.xml
