language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - composer install
  - vendor/bin/doctrine orm:schema-tool:update --force

before_install:
  - pip install codecov
after_success:
  - codecov


script: phpunit --configuration phpunit.xml
