JGimeno\TaskReporter\Domain\Entity\WorkingDay:
  type: entity
  table: working_days
  id:
    id:
      strategy: none
      type: string
  fields:
    date:
      type: string
      nullable: false
  oneToMany:
    tasks:
      orphanRemoval: true
      targetEntity: JGimeno\TaskReporter\Domain\Entity\Task
      mappedBy: workingDay
      cascade: ["persist", "merge", "remove"]