JGimeno\TaskReporter\Domain\Entity\WorkingDay:
  type: entity
  table: working_days
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    date:
      type: string
      nullable: false
  oneToMany:
    tasks:
      targetEntity: JGimeno\TaskReporter\Domain\Entity\Task
      mappedBy: workingDay
      cascade: ["persist", "merge", "remove"]